CREATE DATABASE exam_07;
USE exam_07;

-- TABLE DESIGN

-- INSERT
-- UPDATE
-- DELETE
-- CARS
-- DRIVERS AND CARS
-- NUMBER OF COURSES
-- REGULAR CLIENTS
-- FULL INFO FOR COURSES
-- FIND ALL COURSES BY CLIENT’S PHONE NUMBER
-- FULL INFO FOR ADDRESS