-- EMPLOYEE ADDRESS
SELECT e.employee_id, e.job_title, a.address_id, a.address_text 
FROM employees AS e
JOIN addresses AS a 
ON e.address_id = a.address_id
ORDER BY a.address_id
LIMIT 5;

-- ADDRESSES WITH TOWNS
-- SALES EMPLOYEE
-- EMPLOYEE DEPARTMENTS
-- EMPLOYEE WITHOUT PROJECTS
-- EMPLOYEE HIRED AFTER
-- EMPLOYEE WITH PROJECTS
-- EMPLOYEE 24
-- EMPLOYEE MANAGER
-- EMPLOYEE SUMMARY
-- MIN AVERAGE SALARY
-- HIGHEST PEAKS IN BULGARIA
-- COUNT MOUNTAIN RANGES
-- COUNTRIES WITH RIVERS
-- CONTINENTS AND CURRENCIES
-- COUNTRIES WITHOUT ANY MOUNTAINS 
-- HIGHEST PEAK AND LONGEST RIVER BY COUNTRY