-- EMPLOYEE ADDRESS


-- ADDRESSES WITH TOWNS
-- SALES EMPLOYEE
-- EMPLOYEE DEPARTMENTS
-- EMPLOYEE WITHOUT PROJECTS
-- EMPLOYEE HIRED AFTER
-- EMPLOYEE WITH PROJECTS
-- EMPLOYEE 24
-- EMPLOYEE MANAGER
-- EMPLOYEE SUMMARY
-- MIN AVERAGE SALARY
-- HIGHEST PEAKS IN BULGARIA
-- COUNT MOUNTAIN RANGES
-- COUNTRIES WITH RIVERS
-- CONTINENTS AND CURRENCIES
-- COUNTRIES WITHOUT ANY MOUNTAINS 
-- HIGHEST PEAK AND LONGEST RIVER BY COUNTRY